#pragma once

#include <optional>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace catalyst {

/**
 * @brief Represents a single build step execution.
 *
 * A build step defines a transformation from inputs to a single output using a specific tool.
 */
struct BuildStep {
    /** @brief The tool identifier (e.g., "cc", "cxx", "ld"). */
    std::string_view tool;
    
    /** @brief Raw comma-separated string of input paths. */
    std::string_view inputs;
    
    /** @brief The output file path generated by this step. */
    std::string_view output;
    
    /** 
     * @brief Inputs that are not explicitly parsed but affect the build.
     * Often used for order-only dependencies or implicit system dependencies.
     */
    std::optional<std::vector<std::string_view>> opaque_inputs = std::nullopt;
    
    /** 
     * @brief Inputs discovered dynamically from a dependency file (e.g., .d files from GCC/Clang).
     */
    std::optional<std::vector<std::string_view>> depfile_inputs = std::nullopt;
    
    /** @brief List of explicit input file paths parsed from the `inputs` string. */
    std::vector<std::string_view> parsed_inputs;
};

/** @brief Global definitions/variables for the build (e.g., compiler flags, tool paths). */
using Definitions = std::unordered_map<std::string_view, std::string_view>;

} // namespace catalyst
