#pragma once

#include "cbe/builder.hpp"
#include "cbe/graph.hpp"
#include "cbe/utility.hpp"

#include <shared_mutex>
#include <thread>
#include <vector>

namespace catalyst {

/**
 * @brief Thread-safe cache for file status information (modification times).
 *
 * This cache prevents redundant filesystem calls when checking multiple dependencies
 * for the same file across different threads.
 */
class StatCache {
    struct Entry {
        std::filesystem::path path;
        std::filesystem::file_time_type time;
        std::error_code ec;

        bool operator<(const Entry &other) const;
        bool operator<(const std::filesystem::path &other_path) const;
    };

    std::vector<Entry> cache;
    std::shared_mutex cache_mtx;

public:
    /**
     * @brief Retrieves the last write time for a path, caching the result.
     * @param p The file path to check.
     * @return A pair containing the last write time and any error code.
     */
    std::pair<std::filesystem::file_time_type, std::error_code> get_or_update(const std::filesystem::path &p);
    
    /**
     * @brief Checks if an input file has changed since a given output timestamp.
     * @param input The input file path.
     * @param output_time The timestamp of the output file.
     * @return True if input is newer or stat failed, false otherwise.
     */
    bool changed_since(const std::filesystem::path &input, std::filesystem::file_time_type output_time);
};

struct ExecutorConfig {
    bool dry_run = false; ///< If true, print commands without executing.
    bool clean = false;   ///< If true, clean artifacts instead of building.
    size_t jobs = 0;      ///< Number of parallel jobs (0 = auto-detect).
    std::string build_file = "catalyst.build"; ///< Path to the build manifest.
};

/**
 * @brief Orchestrates the execution of the build graph.
 *
 * This class handles dependency analysis, parallel execution of build steps,
 * and supporting operations like cleaning or generating a compilation database.
 */
class Executor {
public:
    Executor(CBEBuilder &&builder, ExecutorConfig config = {});
    
    /**
     * @brief Executes the build.
     *
     * Performs a parallel walk of the build graph, executing steps whose
     * dependencies are ready and which need rebuilding.
     *
     * @return Success or error.
     */
    Result<void> execute();
    
    /**
     * @brief Removes all output files generated by the build steps.
     * @return Success or error.
     */
    Result<void> clean();
    
    /**
     * @brief Generates a compile_commands.json file for tooling integration.
     * @return Success or error.
     */
    Result<void> emit_compdb();
    
    /**
     * @brief Prints a Graphviz DOT representation of the build graph to stdout.
     * @return Success or error.
     */
    Result<void> emit_graph();

private:
    bool needs_rebuild(const BuildStep &step, StatCache &stat_cache);

    CBEBuilder builder;
    ExecutorConfig config;
    std::vector<std::jthread> pool;
};
} // namespace catalyst
